### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Wangzhanzhan** [trevleyb/TeamCityRallyIntegration#11]
Hello, i am installing the plugin into teamcity 10.0.2. After i intall the plugin into teamcity, i could see the plugin description in External plugins, but i could not see the 'rally integrator' item under integrations of teamcity.
While i also turned on logging by modifying the teamcity-server-log4j.xml file, but i could not see any log about rally in teamcity.
![capture](https://cloud.githubusercontent.com/assets/7919329/19587935/3896ae32-9730-11e6-8f54-1089b2f498a6.PNG)

**Comment by trevleyb** [comment]
Sorry, but I have not updated this application in a long while and no longer have access to Rally to test this against as we moved away from Rally. The source is available for you to view and modify.
