### ISSUE TITLE
is Rally Integrator plugin is compatible with TeamCity Enterprise 10.0.2 version?

### ISSUE THREAD

**Issue by akkji01** [trevleyb/TeamCityRallyIntegration#12]
Team,

We have integration available between Teamcity and Rally tools.

Where as the integration is working fine as expected with Teamcity 9.1.6 and it's not working with 10.0.2 version. Could you please provide the compatibility list for the same?.

Regards,
Jithendar

**Comment by trevleyb** [comment]
Hi there, unfortunately I no longer have access to Rally to test this integration and have not looked at our TeamCity version in a long time so have not tested this against the latest TeamCity. Sorry about this. The source code is here and available for anyone with some Java skills to look at and update.
