### ISSUE TITLE
Rally does not get the build changesets

### ISSUE THREAD

**Issue by naiduv** [trevleyb/TeamCityRallyIntegration#5]
It gets the build information, but not the changesets.
So something is working, something is not.

I do not have a value for RallyScm or RallyBuildDef.
Do you have more info on these?
Thanks!

**Comment by trevleyb** [comment]
You won't get any integration happening if you do not define the RallyScm and RallyBuildDef parameters. 

Every project in rally has a default build definition, normally called Default Build Definition. Add an app, use the GRID object and select Build Definitions as the object to display in the grid. This will allow you to edit the names of the Build Definitions or to add one. Once you do this, you populate RallyBuildDef with this name so it can associate the builds in TC with Rally. 

Same thing with Source Integration. When you use Git or SVN to integrate into Rally it will create a SCM repository. You can view these also by creating a custom app, use GRID and select SCM Repository as the object in the grid. This will give you the SCM names you have integrated. Then populate RallyScm with the appropriate SCM name in rally. 

It does work if you get all the properties setup correctly.

**Comment by naiduv** [comment]
It worked!! Thanks :dancer:
