### ISSUE TITLE
Usernames/Author not being passed through

### ISSUE THREAD

**Issue by Thwaitesy** [trevleyb/TeamCityRallyIntegration#7]
Hi,

I know this project hasn't been touched in a while. However if possible can you suggest a way for me to get the author of the git commit into rally?

Teamcity has the user, just nowhere in your code is there an option to pass up the user.

Cheers,
Sam

**Comment by trevleyb** [comment]
Hi Sam, I haven't looked at this code in a very long time and we are moving away from Rally so don't think I can help you sorry. 

Regards
Trevor

**Comment by Thwaitesy** [comment]
All good mate, thanks for getting back to me.

**Comment by windedge2003** [comment]
Hi , 

so is that means this plugin is not working anymore ?
